using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class BotTransactionPurpose : Object
        {
            /// <summary>
            /// Describes purpose of a transaction with a bot
            /// </summary>
            public class BotTransactionPurposePaidMedia : BotTransactionPurpose
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "botTransactionPurposePaidMedia";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The bought media if the trancastion wasn't refunded
                /// </summary>
                [JsonProperty("media", ItemConverterType = typeof(Converter))]
                public PaidMedia[] Media { get; set; }

                /// <summary>
                /// Bot-provided payload; for bots only
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("payload")]
                public string Payload { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd