using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class BotTransactionPurpose : Object
        {
            /// <summary>
            /// User bought a product from the bot
            /// </summary>
            public class BotTransactionPurposeInvoicePayment : BotTransactionPurpose
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "botTransactionPurposeInvoicePayment";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Information about the bought product; may be null if not applicable
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("product_info")]
                public ProductInfo ProductInfo { get; set; }

                /// <summary>
                /// Invoice payload; for bots only
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("invoice_payload")]
                public byte[] InvoicePayload { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd