using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ChatTransactionPurpose : Object
        {
            /// <summary>
            /// User joined the channel and subscribed to regular payments in Telegram Stars
            /// </summary>
            public class ChatTransactionPurposeJoin : ChatTransactionPurpose
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatTransactionPurposeJoin";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The number of seconds between consecutive Telegram Star debiting
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("period")]
                public int Period { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd