using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ChatTransactionPurpose : Object
        {
            /// <summary>
            /// Describes purpose of a transaction with a supergroup or a channel
            /// </summary>
            public class ChatTransactionPurposePaidMedia : ChatTransactionPurpose
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatTransactionPurposePaidMedia";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Identifier of the corresponding message with paid media; can be 0 or an identifier of a deleted message
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("message_id")]
                public long MessageId { get; set; }

                /// <summary>
                /// The bought media if the trancastion wasn't refunded
                /// </summary>
                [JsonProperty("media", ItemConverterType = typeof(Converter))]
                public PaidMedia[] Media { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd