using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class MessageContent : Object
        {
            /// <summary>
            /// A gift was received or sent by the current user
            /// </summary>
            public class MessageGift : MessageContent
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageGift";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("gift")]
                public Gift Gift { get; set; }

                /// <summary>
                /// Message added to the gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("text")]
                public FormattedText Text { get; set; }

                /// <summary>
                /// Number of Telegram Stars that can be claimed by the receiver instead of the gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("sell_star_count")]
                public long SellStarCount { get; set; }

                /// <summary>
                /// True, if the sender and gift text are shown only to the gift receiver; otherwise, everyone will be able to see them
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_private")]
                public bool IsPrivate { get; set; }

                /// <summary>
                /// True, if the gift is displayed on the user's profile page; only for the receiver of the gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_saved")]
                public bool IsSaved { get; set; }

                /// <summary>
                /// True, if the gift was converted to Telegram Stars; only for the receiver of the gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("was_converted")]
                public bool WasConverted { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd