using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Contains information about subscription to a channel chat paid in Telegram Stars
        /// </summary>
        public partial class StarSubscription : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "starSubscription";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Unique identifier of the subscription
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("id")]
            public string Id { get; set; }

            /// <summary>
            /// Identifier of the channel chat that is subscribed
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Point in time (Unix timestamp) when the subscription will expire or expired
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("expiration_date")]
            public int ExpirationDate { get; set; }

            /// <summary>
            /// True, if the subscription is active and the user can use the method reuseStarSubscription to join the subscribed chat again
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_reuse")]
            public bool CanReuse { get; set; }

            /// <summary>
            /// True, if the subscription was canceled
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_canceled")]
            public bool IsCanceled { get; set; }

            /// <summary>
            /// True, if the subscription expires soon and there are no enough Telegram Stars on the user's balance to extend it
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_expiring")]
            public bool IsExpiring { get; set; }

            /// <summary>
            /// The invite link that can be used to renew the subscription if it has been expired; may be empty, if the link isn't available anymore
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("invite_link")]
            public string InviteLink { get; set; }

            /// <summary>
            /// The subscription plan
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("pricing")]
            public StarSubscriptionPricing Pricing { get; set; }
        }
    }
}
// REUSE-IgnoreEnd