using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Contains information about Telegram Stars earned by a bot or a chat
        /// </summary>
        public partial class StarRevenueStatus : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "starRevenueStatus";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Total number of Telegram Stars earned
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("total_count")]
            public long TotalCount { get; set; }

            /// <summary>
            /// The number of Telegram Stars that aren't withdrawn yet
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("current_count")]
            public long CurrentCount { get; set; }

            /// <summary>
            /// The number of Telegram Stars that are available for withdrawal
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("available_count")]
            public long AvailableCount { get; set; }

            /// <summary>
            /// True, if Telegram Stars can be withdrawn now or later
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("withdrawal_enabled")]
            public bool WithdrawalEnabled { get; set; }

            /// <summary>
            /// Time left before the next withdrawal can be started, in seconds; 0 if withdrawal can be started now
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("next_withdrawal_in")]
            public int NextWithdrawalIn { get; set; }
        }
    }
}
// REUSE-IgnoreEnd