using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class StarTransactionPartner : Object
        {
            /// <summary>
            /// The transaction is a transaction with a supergroup or a channel chat
            /// </summary>
            public class StarTransactionPartnerChat : StarTransactionPartner
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "starTransactionPartnerChat";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Identifier of the chat
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                /// <summary>
                /// Purpose of the transaction
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("purpose")]
                public ChatTransactionPurpose Purpose { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd