using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class UserTransactionPurpose : Object
        {
            /// <summary>
            /// The current user sent a gift to another user
            /// </summary>
            public class UserTransactionPurposeGiftSend : UserTransactionPurpose
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "userTransactionPurposeGiftSend";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("gift")]
                public Gift Gift { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd