using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Sells a gift received by the current user for Telegram Stars
        /// </summary>
        public class SellGift : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "sellGift";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the user that sent the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("sender_user_id")]
            public long SenderUserId { get; set; }

            /// <summary>
            /// Identifier of the message with the gift in the chat with the user
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("message_id")]
            public long MessageId { get; set; }
        }

        /// <summary>
        /// Sells a gift received by the current user for Telegram Stars
        /// </summary>
        public static Task<Ok> SellGiftAsync(
            this Client client, long senderUserId = default, long messageId = default)
        {
            return client.ExecuteAsync(new SellGift
            {
                SenderUserId = senderUserId, MessageId = messageId
            });
        }
    }
}
// REUSE-IgnoreEnd