using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Send a gift to another user
        /// </summary>
        public class SendGift : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "sendGift";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the gift to send
            /// </summary>
            [JsonConverter(typeof(Converter.Int64))]
            [JsonProperty("gift_id")]
            public long GiftId { get; set; }

            /// <summary>
            /// Identifier of the user that will receive the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("user_id")]
            public long UserId { get; set; }

            /// <summary>
            /// Text to show along with the gift; 0-getOption("gift_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("text")]
            public FormattedText Text { get; set; }

            /// <summary>
            /// Pass true to show the current user as sender and gift text only to the gift receiver; otherwise, everyone will be able to see them
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_private")]
            public bool IsPrivate { get; set; }
        }

        /// <summary>
        /// Send a gift to another user
        /// </summary>
        public static Task<Ok> SendGiftAsync(
            this Client client, long giftId = default, long userId = default, FormattedText text = default, bool isPrivate = default)
        {
            return client.ExecuteAsync(new SendGift
            {
                GiftId = giftId, UserId = userId, Text = text, IsPrivate = isPrivate
            });
        }
    }
}
// REUSE-IgnoreEnd