using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Toggles whether a gift is shown on the current user's profile page
        /// </summary>
        public class ToggleGiftIsSaved : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "toggleGiftIsSaved";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the user that sent the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("sender_user_id")]
            public long SenderUserId { get; set; }

            /// <summary>
            /// Identifier of the message with the gift in the chat with the user
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("message_id")]
            public long MessageId { get; set; }

            /// <summary>
            /// Pass true to display the gift on the user's profile page; pass false to remove it from the profile page
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_saved")]
            public bool IsSaved { get; set; }
        }

        /// <summary>
        /// Toggles whether a gift is shown on the current user's profile page
        /// </summary>
        public static Task<Ok> ToggleGiftIsSavedAsync(
            this Client client, long senderUserId = default, long messageId = default, bool isSaved = default)
        {
            return client.ExecuteAsync(new ToggleGiftIsSaved
            {
                SenderUserId = senderUserId, MessageId = messageId, IsSaved = isSaved
            });
        }
    }
}
// REUSE-IgnoreEnd